name: dart_extras
description: Dart Extensions
version: 0.0.1
author: mobiplay

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  equatable: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
